### ISSUE TITLE
only dumps first 28 groups, ignores rest

### ISSUE THREAD

**Issue by shiypc** [tscanlin/svgsplit#6]
i'm trying to dump svgs from a polymer iconset, and even though all of the icons appears in the preview list, only 28 are included in the final downloaded archive. i have attached the file where this happens, and i'm using firefox 115 on macOS.

![yt-icons](https://github.com/tscanlin/svgsplit/assets/26725277/df429037-6f41-4b9a-9c91-47500088f814)

**Comment by tscanlin** [comment]
Hey, thanks for opening this issue and sorry for the late reply. I was out of town but just got back today.

I pushed some tweaks to show links to download the files at the bottom of the preview area since it is splitting to multiple files and can't download them all automatically. Let me know if you still run into issues or if this helps solve the issue. Thanks!

**Comment by shiypc** [comment]
this does fix it, all of the SVGs i needed are there, thanks!
